version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: db_gerenciador
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: db_gerenciador_aluguel
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: